# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-reactivated_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='delegate',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
