# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160704_1517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Families',
            new_name='Family',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='user_id',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
