# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 18:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20160704_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='delegate',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
